name: HmtNote
channels:
  - bioconda
  - anaconda
  - defaults
dependencies:
  - asn1crypto=0.24.0=py36_0
  - atomicwrites=1.3.0=py_0
  - attrs=18.2.0=py36h28b3542_0
  - blas=1.0=mkl
  - ca-certificates=2019.1.23=0
  - certifi=2018.11.29=py36_0
  - chardet=3.0.4=py36_1
  - click=7.0=py36_0
  - coloredlogs=10.0=py36_0
  - cyvcf2=0.10.0=py36h355e19c_0
  - humanfriendly=4.17=py36_0
  - idna=2.8=py36_0
  - intel-openmp=2019.1=144
  - mkl=2019.1=144
  - more-itertools=5.0.0=py36_0
  - pip=19.0.3=py36_0
  - pluggy=0.9.0=py36_0
  - py=1.8.0=py36_0
  - pycparser=2.19=py36_0
  - pyopenssl=19.0.0=py36_0
  - requests=2.21.0=py36_0
  - setuptools=40.8.0=py36_0
  - six=1.12.0=py36_0
  - urllib3=1.24.1=py36_0
  - wheel=0.33.1=py36_0

